server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    client_max_body_size 2m;

    location /build/ { expires 1y; add_header Cache-Control "public, immutable"; }

    location / { try_files $uri $uri/ /index.php?$query_string; }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* { deny all; }
}
